# Generated by Django 4.2.30 on 2026-07-01 07:02

import apps.common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features', models.TextField(blank=True, help_text='Comma-separated list of features')),
                ('specifications', models.TextField(blank=True, help_text='Comma-separated list of specifications')),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
