# Generated by Django 4.2.30 on 2026-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_milestone_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
