# Generated by Django 4.2.30 on 2026-07-03 16:58

import apps.common.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options_stat_icon_alter_about_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairmanMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Chairman', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': "Chairman's Message",
                'verbose_name_plural': "Chairman's Message",
            },
        ),
    ]
