# Generated by Django 4.2.30 on 2026-07-03 17:08

import apps.common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_map', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('is_head_office', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Branch Office',
                'verbose_name_plural': 'Branch Offices',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Comma-separated list of requirements')),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('service_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('product_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to=apps.common.utils.upload_to)),
                ('cover_letter', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contact.career')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
