# Generated by Django 4.2.30 on 2026-06-30 18:16

import apps.common.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to=apps.common.utils.upload_to)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('company_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(upload_to=apps.common.utils.upload_to)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField()),
                ('google_map', models.URLField(blank=True)),
                ('copyright', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=apps.common.utils.upload_to)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('is_fullscreen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X')], max_length=30)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('client_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('is_footer', models.BooleanField(default=False, help_text='Show in footer as well')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navbarlink')),
            ],
            options={
                'verbose_name': 'Navbar Link',
                'verbose_name_plural': 'Navbar Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=100)),
                ('column', models.PositiveIntegerField(default=1, help_text='Footer column (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('links', models.ManyToManyField(blank=True, related_name='footer_sections', to='core.navbarlink')),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['column', 'order'],
            },
        ),
    ]
