# Generated by Django 4.2.30 on 2026-07-03 16:58
# Hand-edited: SEOSetting had no rows, so the PK type change (BigAutoField -> UUIDField)
# is done as a drop/recreate instead of an in-place ALTER COLUMN, which Postgres
# cannot do for bigint -> uuid (no implicit cast exists).

import apps.common.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='SEOSetting'),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.upload_to)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
