# Generated by Django 4.2.30 on 2026-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seosetting_created_at_seosetting_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='singleton_guard',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
